# Generated by Django 5.1.6 on 2025-03-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Player", "Player"),
                            ("Game Keeper", "Game Keeper"),
                            ("Developer", "Developer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
