# Generated by Django 5.1.6 on 2025-03-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0002_accesscode"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertask",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertask",
            unique_together={("user", "task")},
        ),
    ]
