# Generated by Django 5.1.6 on 2025-02-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0004_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="is_location_based",
            new_name="requireScan",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="photo_required",
            new_name="requiresUpload",
        ),
        migrations.RemoveField(
            model_name="task",
            name="qr_code",
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.AlterField(
            model_name="task",
            name="points",
            field=models.IntegerField(),
        ),
    ]
