# Generated by Django 5.1.6 on 2025-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0004_alter_usertask_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesscode",
            name="role",
            field=models.CharField(
                choices=[
                    ("Player", "Player"),
                    ("GameKeeper", "GameKeeper"),
                    ("Developer", "Developer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Player", "Player"),
                    ("GameKeeper", "GameKeeper"),
                    ("Developer", "Developer"),
                ],
                default="Player",
                max_length=20,
                null=True,
            ),
        ),
    ]
