# Generated by Django 5.1.6 on 2025-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0005_rename_is_location_based_task_requirescan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="requireScan",
        ),
        migrations.RemoveField(
            model_name="task",
            name="requiresUpload",
        ),
        migrations.AddField(
            model_name="task",
            name="requires_scan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="requires_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="BingoTask",
        ),
    ]
