# Generated by Django 5.1.6 on 2025-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0007_taskbonus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Player", "Player"),
                    ("GameKeeper", "GameKeeper"),
                    ("Developer", "Developer"),
                ],
                default="Player",
                max_length=20,
            ),
        ),
    ]
