# Generated by Django 5.1.6 on 2025-03-14 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0007_taskbonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboard",
            name="last_reset",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="monthly_points",
            field=models.IntegerField(default=0),
        ),
    ]
