# Generated by Django 5.1.6 on 2025-02-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bingo", "0007_rename_profile_user_role_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rank",
            field=models.CharField(default="Unranked", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
    ]
